// react-app/src/components/HeaderBarBrand.js
import React from 'react';
import { NavLink } from 'react-router-dom';

const HeaderBarBrand = () => (
  <div className="navbar-brand">
    <a
      className="navbar-item"
      href="https://reactjs.org/"
      target="_blank"
      rel="noopener noreferrer"
    >
      <i className="fab js-logo fa-react fa-2x" aria-hidden="true" />
    </a>
    <NavLink to="/" className="navbar-item nav-home">
      <span className="brand-first">MY</span>
      <span className="brand-second">APPS</span>
    </NavLink>
  </div>
);

export default HeaderBarBrand;

// svelte-app/src/components/HeaderBarBrand.svelte
<div class="navbar-brand">
  <a
    class="navbar-item"
    href="https://svelte.dev/"
    target="_blank"
    rel="noopener noreferrer">
    <img src="./svelte-icon.png" alt="Svelte" />
  </a>
  <router-link to="/" class="navbar-item nav-home">
    <span class="brand-first">MY</span>
    <span class="brand-second">APPS</span>
  </router-link>
</div>
